
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 25 05:08:23 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 27;
  public static final int GREATER_OR_EQUAL = 47;
  public static final int CONST = 26;
  public static final int CASE = 31;
  public static final int NOTEQUAL = 49;
  public static final int GREATER = 46;
  public static final int CONTINUE = 39;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int DAND = 19;
  public static final int LESS = 48;
  public static final int MINUS = 24;
  public static final int RPAREN = 7;
  public static final int SCALAR = 15;
  public static final int LESS_OR_EQUAL = 45;
  public static final int COMMA = 11;
  public static final int CLASS = 37;
  public static final int INC = 33;
  public static final int DIV = 21;
  public static final int QUESTION_MARK = 38;
  public static final int PLUS = 10;
  public static final int IF = 51;
  public static final int DOT = 20;
  public static final int DOR = 35;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 25;
  public static final int EQUAL = 8;
  public static final int TRUE = 40;
  public static final int ISEQUAL = 44;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int NUMBER = 42;
  public static final int MOD = 22;
  public static final int IDENT = 43;
  public static final int BREAK = 30;
  public static final int VOID = 13;
  public static final int SWITCH = 23;
  public static final int COLON = 16;
  public static final int ELSE = 52;
  public static final int LBRACE = 3;
  public static final int ENUM = 28;
  public static final int READ = 32;
  public static final int CHARCONST = 50;
  public static final int WHILE = 34;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int DEC = 14;
  public static final int FALSE = 41;
  public static final int DO = 36;
  public static final int PRINT = 12;
}

